title: 'Desarrollo de Sistemas Informáticos'
subtitle: 'Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2018/2019'
theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate fatal
# theme: jekyll-theme-modernist
# theme: jekyll-theme-leap-day
description: '3º. 2 cuatrimestre. Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2018/2019'
show_downloads: false
exclude: ['/Users/casiano/campus-virtual/1819/dsi1819/introduccion/tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-filesystem-ch2/wrangling-the-fs-ale-ivan', '/Users/casiano/campus-virtual/1819/dsi1819/introduccion/tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-filesystem-ch2/chapter20-node-ejs', '/Users/casiano/campus-virtual/1819/dsi1819/introduccion/tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-the-right-way/filesystem-chapter-2', '/Users/casiano/campus-virtual/1819/dsi1819/introduccion/tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-the-right-way/commanding-databases-chapter-6/sol-nodejs-the-right-way']
