title: 'Desarrollo de Sistemas Informáticos'
subtitle: 'Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2018/2019'
theme: jekyll-theme-midnight
description: '3º. 2 cuatrimestre. Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2018/2019'
show_downloads: false